"""YAML writer for the new error model + optional debug TSVs.

Output paths:
  - User model YAML: ``~/.config/speconsense/error_models/{name}.yaml``
    (creates the directory if it does not yet exist; refuses to overwrite
    without ``--force``).
  - Debug TSVs under ``--debug-dir`` (optional): mirrors the
    ``~/mm/analysis/hp_error_rate/output_*/tables/`` layout for continuity
    with the original analysis pipeline.
"""

from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from speconsense import qctx

from .analyze import ContextResult
from .extract import NonHPCounts
from .nonhp import NonHPBin
from .selection import SpecimenRecord


def _format_yaml(
    name: str,
    chemistry: str,
    basecaller: str,
    source: str,
    dataset: str,
    description: Optional[str],
    rates: Dict[str, float],
) -> str:
    """Render the YAML body matching the shipped models' layout exactly.

    The shipped models use a header block of `#` comments above the
    name/chemistry/basecaller/source/dataset fields and the rates: mapping.
    We follow the same structure so user models remain visually consistent
    with bundled models.
    """
    lines: List[str] = []
    lines.append(f"# Context-specific error rate table for {basecaller} / {chemistry}.")
    lines.append("#")
    lines.append(f"# Generated by speconsense-fit-error-model on "
                 f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.")
    if description:
        lines.append("#")
        for line in description.splitlines():
            lines.append(f"# {line}".rstrip())
    lines.append("#")
    lines.append("# Lookup keys used by speconsense:")
    lines.append("#   non-hp-sub         Substitution at a non-HP position")
    lines.append("#   non-hp-indel       Indel at a non-HP position")
    lines.append("#   hp-l{N}            Length change in an HP run of length N (1..5)")
    lines.append("# HP runs of length >= 6 are evaluated by blanket HP")
    lines.append("# normalization rather than CER (HP paper §8.1).")
    lines.append("")
    lines.append(f"name: {name}")
    lines.append(f"chemistry: {chemistry}")
    lines.append(f"basecaller: {basecaller}")
    lines.append(f"source: {source}")
    lines.append(f"dataset: {dataset}")
    lines.append("")
    lines.append("rates:")
    # Ordering matches the shipped models for diff-friendliness.
    ordered_keys = [
        "non-hp-sub",
        "non-hp-indel",
        "hp-l1",
        "hp-l2",
        "hp-l3",
        "hp-l4",
        "hp-l5",
    ]
    for key in ordered_keys:
        if key in rates:
            label = f"{key}:"
            lines.append(f"  {label:<14} {rates[key]:.4f}")
    lines.append("")
    return "\n".join(lines)


def write_model(
    name: str,
    rates: Dict[str, float],
    *,
    chemistry: str,
    basecaller: str,
    source: str,
    dataset: str,
    description: Optional[str] = None,
    force: bool = False,
    dry_run: bool = False,
) -> Tuple[Path, str]:
    """Write the YAML to ``~/.config/speconsense/error_models/{name}.yaml``.

    Returns ``(path, yaml_text)``. ``dry_run=True`` returns the rendered
    text without touching disk. Refuses to overwrite an existing file
    without ``force=True``.
    """
    user_dir = qctx.user_dir()
    user_dir.mkdir(parents=True, exist_ok=True)
    path = user_dir / f"{name}.yaml"

    text = _format_yaml(
        name=name,
        chemistry=chemistry,
        basecaller=basecaller,
        source=source,
        dataset=dataset,
        description=description,
        rates=rates,
    )

    if dry_run:
        return path, text

    if path.exists() and not force:
        raise FileExistsError(
            f"{path} already exists. Pass --force to overwrite, or pick a "
            f"different --name."
        )
    path.write_text(text)
    return path, text


# ---------------------------------------------------------------------------
# Debug TSV outputs (optional, via --debug-dir)
# ---------------------------------------------------------------------------


def _write_tsv(path: Path, rows: List[List[str]], header: List[str]) -> None:
    with open(path, "w") as f:
        f.write("\t".join(header) + "\n")
        for row in rows:
            f.write("\t".join(row) + "\n")


def write_qualifying_specimens_tsv(
    path: Path,
    qualifying: List[SpecimenRecord],
) -> None:
    rows = []
    for r in qualifying:
        rows.append([
            r.name,
            str(r.primary_m or ""),
            f"{r.primary_err_factor:.4f}" if r.primary_err_factor is not None else "",
            r.error_model or "",
            str(r.total_input_reads or ""),
        ])
    _write_tsv(path, rows, ["specimen", "primary_RiC", "primary_err_factor",
                            "error_model", "total_input_reads"])


def write_hp_rates_tsv(
    path: Path,
    results: Dict[Tuple[str, int], ContextResult],
) -> None:
    rows = []
    for (base, length) in sorted(results.keys()):
        r = results[(base, length)]
        rows.append([
            base, str(length), str(r.n_runs), str(r.n_obs),
            f"{r.frac_correct:.6f}",
            f"{r.frac_minus1:.6f}", f"{r.frac_plus1:.6f}",
            f"{r.frac_minus2plus:.6f}", f"{r.frac_plus2plus:.6f}",
            f"{r.mean_called:.3f}", f"{r.std_called:.3f}",
        ])
    _write_tsv(path, rows, ["base", "hp_length", "n_runs", "n_obs",
                            "frac_correct", "frac_minus1", "frac_plus1",
                            "frac_minus2plus", "frac_plus2plus",
                            "mean_called", "std_called"])


def write_hp_distributions_tsv(
    path: Path,
    results: Dict[Tuple[str, int], ContextResult],
) -> None:
    rows = []
    for (base, length) in sorted(results.keys()):
        r = results[(base, length)]
        if r.n_obs == 0:
            continue
        for delta in sorted(r.distribution.keys()):
            count = r.distribution[delta]
            frac = count / r.n_obs
            rows.append([base, str(length), str(delta), str(count), f"{frac:.6f}"])
    _write_tsv(path, rows, ["base", "hp_length", "delta", "count", "fraction"])


def write_nonhp_rates_tsv(
    path: Path,
    pooled: NonHPCounts,
    by_bin: Dict[str, NonHPBin],
) -> None:
    rows = []
    denom_or = lambda counts: counts.matches + counts.substitutions + counts.deletions  # noqa: E731
    for label, bin_ in by_bin.items():
        d = denom_or(bin_.counts)
        if d <= 0:
            continue
        rows.append([
            label, str(bin_.n_clusters), str(bin_.n_reads), str(d),
            f"{bin_.counts.substitutions/d:.6f}",
            f"{bin_.counts.deletions/d:.6f}",
            f"{bin_.counts.insertions/d:.6f}",
        ])
    d_pooled = denom_or(pooled)
    if d_pooled > 0:
        rows.append([
            "POOLED", "", "", str(d_pooled),
            f"{pooled.substitutions/d_pooled:.6f}",
            f"{pooled.deletions/d_pooled:.6f}",
            f"{pooled.insertions/d_pooled:.6f}",
        ])
    _write_tsv(path, rows, ["bin", "n_clusters", "n_reads", "n_obs",
                            "sub_rate", "del_rate", "ins_rate"])


def write_debug_outputs(
    debug_dir: str,
    qualifying: List[SpecimenRecord],
    raw_hp: Dict[Tuple[str, int], ContextResult],
    filtered_hp: Dict[Tuple[str, int], ContextResult],
    pooled_nonhp: NonHPCounts,
    nonhp_by_bin: Dict[str, NonHPBin],
) -> Path:
    """Write all five debug TSVs into ``debug_dir`` (created if needed).

    Returns the directory path for the caller's summary log.
    """
    out = Path(debug_dir)
    out.mkdir(parents=True, exist_ok=True)
    write_qualifying_specimens_tsv(out / "qualifying_specimens.tsv", qualifying)
    write_hp_rates_tsv(out / "hp_error_rates.tsv", raw_hp)
    write_hp_rates_tsv(out / "hp_error_rates_filtered.tsv", filtered_hp)
    write_hp_distributions_tsv(out / "hp_distributions.tsv", raw_hp)
    write_hp_distributions_tsv(out / "hp_distributions_filtered.tsv", filtered_hp)
    write_nonhp_rates_tsv(out / "non_hp_error_rates.tsv", pooled_nonhp, nonhp_by_bin)
    return out
